[package]
name = "vault-litesvm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
borsh = { version = "0.10.3", features = ["derive"] }
solana-program = "1.18.26"

[dev-dependencies]
litesvm = "0.2.1"
solana-sdk = "1.18.26"