[package]
name = "vault-litesvm"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.7"
solana-program = "3.0.0"
solana-sdk = "3.0.0"
solana-system-interface = { version = "2.0.0", features = ["bincode"] }

[dev-dependencies]
litesvm = "0.8.1"
